import type { GuideSection } from '@/types';

// Default guide content used when no admin-managed sections exist in the database.
// Each section has a deterministic id prefix 'default-' so we can distinguish
// defaults from DB rows when merging.

export const defaultGuideSections: Omit<GuideSection, 'created_by' | 'created_at' | 'updated_at'>[] = [
  // ─── Getting Started ─────────────────────────────────────
  {
    id: 'default-gs-1',
    title: 'Welcome to Titus 2:4',
    icon: 'Heart',
    description: 'Learn what this app is all about and how it can bless your journey.',
    content: `Titus 2:4 is a community app built for women pursuing God's purpose for their lives. Whether you're single, engaged, or preparing for marriage, this is your space to grow, pray, and encourage one another.\n\nThe name comes from Titus 2:4 — "Then they can urge the younger women to love their husbands and children." This app is about building a sisterhood of faith, accountability, and love.\n\nExplore the features below to get started!`,
    category: 'getting_started',
    display_order: 1,
    is_active: true,
  },
  {
    id: 'default-gs-2',
    title: 'Setting Up Your Profile',
    icon: 'User',
    description: 'Make sure your sisters can find and connect with you.',
    content: `Your profile is your identity in this community. Here's how to set it up:\n\n1. Tap "Profile" in the bottom navigation bar\n2. Tap the camera icon on your avatar to upload a photo\n3. Tap "Edit Profile" to add your name, city, country, and a short bio\n4. Set your prayer focus so sisters know how to pray for you\n5. Add your birthday and anniversary if you'd like the community to celebrate with you\n\nYou can also switch between light and dark mode from your profile page.`,
    category: 'getting_started',
    display_order: 2,
    is_active: true,
  },
  {
    id: 'default-gs-3',
    title: 'Your Daily Routine',
    icon: 'Sparkles',
    description: 'Start each day with intention using Check-In and Devotional.',
    content: `We encourage every sister to build a daily rhythm:\n\n1. Check-In — Share how you're feeling today and write a gratitude note. This takes just 30 seconds and helps you stay connected to your emotions and to God.\n\n2. Daily Devotional — Read the devotional for the day, reflect on the scripture, and let the affirmation and prayer guide your morning.\n\nBoth of these are available from the Home screen tiles. Consistency earns points and builds your streak!`,
    category: 'getting_started',
    display_order: 3,
    is_active: true,
  },
  {
    id: 'default-gs-4',
    title: 'Connecting with Sisters',
    icon: 'Users',
    description: 'Find your sisters, send messages, and build real friendships.',
    content: `You're not alone in this journey. Here's how to connect:\n\n- Directory — Browse all members, see their city and country, and tap to view their profile\n- Messages — Send private messages to any sister for encouragement or accountability\n- Prayer Partners — Each week you'll be paired with a prayer partner. Pray for each other daily!\n- Pods — Join a small accountability group to share check-ins and walk together\n\nDon't be shy — reach out to someone new this week!`,
    category: 'getting_started',
    display_order: 4,
    is_active: true,
  },

  // ─── Features ────────────────────────────────────────────
  {
    id: 'default-ft-1',
    title: 'Community Feed',
    icon: 'Users',
    description: 'Share encouragement, testimonies, and updates with your sisters.',
    content: `The Community feed is the heart of Titus 2:4. Here you can:\n\n- Share a post with text or an image\n- React to posts with Amen, Heart, Praise, Strength, or Fire\n- Comment on posts and reply to comments\n- See pinned announcements from leadership\n\nKeep it uplifting and God-honouring. This is a safe space for every sister.`,
    category: 'features',
    display_order: 10,
    is_active: true,
  },
  {
    id: 'default-ft-2',
    title: 'Prayer Wall',
    icon: 'Heart',
    description: 'Submit prayer requests and pray for your sisters.',
    content: `The Prayer Wall is where sisters bear one another's burdens:\n\n- Submit a prayer request with a category (Family, Health, Work, etc.)\n- Choose to post anonymously if you prefer\n- Tap "Praying" on someone else's request to let them know you're lifting them up\n- Add an encouragement message when you pray\n- Mark your prayer as answered when God moves!\n\nEvery prayer counts. Your sisters need your intercession.`,
    category: 'features',
    display_order: 11,
    is_active: true,
  },
  {
    id: 'default-ft-3',
    title: 'Events',
    icon: 'Calendar',
    description: 'Stay updated on upcoming gatherings and RSVP.',
    content: `Never miss a gathering:\n\n- View all upcoming events with date, time, and location\n- RSVP as "Coming", "Maybe", or "No"\n- See what to bring if specified\n- Set a reminder so you don't forget\n\nEvents are created by your leadership team. Check back regularly for new gatherings!`,
    category: 'features',
    display_order: 12,
    is_active: true,
  },
  {
    id: 'default-ft-4',
    title: 'Daily Check-In',
    icon: 'Heart',
    description: 'Share your mood and gratitude each day.',
    content: `The daily check-in helps you stay aware of your emotional and spiritual state:\n\n- Choose a mood emoji that represents how you're feeling\n- Write a short gratitude note\n- Build a streak by checking in every day\n- Earn points for consistency\n\nLeadership can see overall mood trends (not individual entries) to better support the community.`,
    category: 'features',
    display_order: 13,
    is_active: true,
  },
  {
    id: 'default-ft-5',
    title: 'Daily Devotional',
    icon: 'Sparkles',
    description: 'Read scripture, reflect, and pray each day.',
    content: `Each day features a fresh devotional with:\n\n- A theme to focus on\n- A scripture reference and text\n- A reflection to meditate on\n- An affirmation to speak over yourself\n- A prayer to pray\n\nDevotionals are created by leadership or rotate from our built-in content library.`,
    category: 'features',
    display_order: 14,
    is_active: true,
  },
  {
    id: 'default-ft-6',
    title: 'Pods (Accountability Groups)',
    icon: 'Users',
    description: 'Join a small group for deeper accountability.',
    content: `Pods are small accountability groups of up to 5 sisters:\n\n- Each pod has a leader and members\n- Post check-ins to your pod to share how you're doing\n- Pods are assigned by leadership\n- This is your inner circle for honest, vulnerable sharing\n\nIf you're not in a pod yet, ask your elder or leadership to assign you to one.`,
    category: 'features',
    display_order: 15,
    is_active: true,
  },
  {
    id: 'default-ft-7',
    title: 'Ask the Elders',
    icon: 'HelpCircle',
    description: 'Submit anonymous questions for wisdom and guidance.',
    content: `Have a question you're not comfortable asking publicly?\n\n- Submit a question anonymously\n- Choose a category (General, Relationships, Faith, etc.)\n- Elders will review and answer your question\n- All answered questions are visible to the community for shared learning\n\nNo question is too small or too personal. Your elders are here for you.`,
    category: 'features',
    display_order: 16,
    is_active: true,
  },
  {
    id: 'default-ft-8',
    title: 'Messages',
    icon: 'MessageCircle',
    description: 'Private conversations with your sisters.',
    content: `Send and receive private messages:\n\n- Tap on any sister's profile or find them in the Directory\n- Send a message to start a conversation\n- All conversations are listed in the Messages section\n- You'll receive a notification when someone messages you\n\nUse messages for personal encouragement, prayer, and fellowship.`,
    category: 'features',
    display_order: 17,
    is_active: true,
  },
  {
    id: 'default-ft-9',
    title: 'Bible Study',
    icon: 'BookOpen',
    description: 'Enrol in multi-day studies and grow in the Word.',
    content: `Bible Studies are multi-day guided plans:\n\n- Browse available studies and enrol\n- Each day has a scripture, reflection prompt, and space to journal\n- Track your progress day by day\n- Earn points and badges for completing study days\n\nStudies are created by leadership. New studies are added regularly!`,
    category: 'features',
    display_order: 18,
    is_active: true,
  },
  {
    id: 'default-ft-10',
    title: 'Testimonies',
    icon: 'PartyPopper',
    description: 'Celebrate what God is doing in your life.',
    content: `The Testimonies section is for celebrating God's faithfulness:\n\n- Share a testimony with a category (Answered Prayer, Healing, Breakthrough, etc.)\n- Celebrate other sisters' testimonies\n- Post anonymously if you prefer\n\nYour testimony could be the encouragement someone else needs today.`,
    category: 'features',
    display_order: 19,
    is_active: true,
  },

  // ─── FAQ ─────────────────────────────────────────────────
  {
    id: 'default-faq-1',
    title: 'How do I change my profile photo?',
    icon: 'Camera',
    description: 'Update your avatar in a few taps.',
    content: `Go to Profile (bottom navigation) and tap the camera icon on your current avatar. Select a photo from your device and it will be uploaded automatically. The image is optimised for fast loading.`,
    category: 'faq',
    display_order: 100,
    is_active: true,
  },
  {
    id: 'default-faq-2',
    title: 'How do points and streaks work?',
    icon: 'Trophy',
    description: 'Understand the gamification and leaderboard system.',
    content: `You earn points for engaging with the community:\n\n- Daily check-in: 5 points\n- Reading devotional: 5 points\n- Sharing a post: 10 points\n- Leaving a comment: 3 points\n- Submitting a prayer: 10 points\n- Praying for a sister: 5 points\n- Sharing a testimony: 15 points\n- Completing a study day: 10 points\n- Attending an event: 20 points\n- Streak bonus: 10 points\n\nYour rank title changes as you earn more points. Check the Leaderboard to see where you stand!`,
    category: 'faq',
    display_order: 101,
    is_active: true,
  },
  {
    id: 'default-faq-3',
    title: 'Can I post anonymously?',
    icon: 'Eye',
    description: 'Learn where anonymous posting is available.',
    content: `Yes! You can post anonymously in two places:\n\n- Prayer Wall — Toggle "Post anonymously" when submitting a prayer request\n- Ask the Elders — All questions are anonymous by default\n\nCommunity posts and testimonies also have an anonymous option. Your identity is never revealed for anonymous posts.`,
    category: 'faq',
    display_order: 102,
    is_active: true,
  },
  {
    id: 'default-faq-4',
    title: 'How do I switch between light and dark mode?',
    icon: 'Moon',
    description: 'Toggle the app theme.',
    content: `Go to your Profile page and you'll see a card with "Light Mode" or "Dark Mode". Tap the button to switch. Your preference is saved to your account and applies across all devices.`,
    category: 'faq',
    display_order: 103,
    is_active: true,
  },
  {
    id: 'default-faq-5',
    title: 'Who can see my data?',
    icon: 'Shield',
    description: 'Understand privacy and visibility in the app.',
    content: `Your privacy matters:\n\n- Profile info (name, city, about) is visible to all members\n- Birthday and anniversary are only shown if you enable "Show birthday to community"\n- Daily check-in moods are only visible to you and leadership\n- Prayer requests are visible to all unless you post anonymously\n- Messages are private between you and the recipient\n- Follow-up notes are only visible to leadership\n\nAll data is stored securely with Supabase and protected by row-level security policies.`,
    category: 'faq',
    display_order: 104,
    is_active: true,
  },
  {
    id: 'default-faq-6',
    title: 'How do I get assigned to a prayer partner?',
    icon: 'HeartHandshake',
    description: 'Learn about the weekly prayer partner system.',
    content: `Prayer partners are assigned automatically each week. The system pairs you with a different sister so you can pray for each other daily.\n\nYou'll see your current prayer partner on the Prayer Partner page. If you haven't been paired yet, check back at the start of the next week.\n\nUse Messages to reach out to your prayer partner and share specific prayer requests.`,
    category: 'faq',
    display_order: 105,
    is_active: true,
  },
  {
    id: 'default-faq-7',
    title: 'What do I do if I need help?',
    icon: 'HelpCircle',
    description: 'Get support from leadership.',
    content: `If you need help with anything:\n\n1. Use "Ask the Elders" to submit a question anonymously\n2. Send a direct message to any elder or admin\n3. Reach out to your pod leader for accountability support\n4. Contact your prayer partner for spiritual encouragement\n\nYour leadership team is here to support you. Don't hesitate to reach out.`,
    category: 'faq',
    display_order: 106,
    is_active: true,
  },
];
